### ISSUE TITLE
NullPointerError is reported 

### ISSUE THREAD

**Issue by abhayjatindoshi** [wakatime/netbeans-wakatime#12]
A nullPointer exception was reported on first launch after installing and it never asked me for the API key

**Comment by alanhamlett** [comment]
Can you find the full traceback with line number of the exception?

**Comment by abhayjatindoshi** [comment]
java.lang.NullPointerException
	at org.wakatime.netbeans.plugin.WakaTime.isDebugEnabled(WakaTime.java:186)
	at org.wakatime.netbeans.plugin.WakaTime.run(WakaTime.java:62)
[catch] at org.netbeans.core.windows.WindowManagerImpl$Exclusive$1.run(WindowManagerImpl.java:1563)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:744)
	at java.awt.EventQueue.access$400(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:697)
	at java.awt.EventQueue$3.run(EventQueue.java:691)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:714)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)



//This is what i found..

**Comment by alanhamlett** [comment]
From those line numbers, it looks like you're using an older version of the plugin... can you make sure to upgrade to v4.0.6?

**Comment by abhayjatindoshi** [comment]
https://github.com/wakatime/netbeans-wakatime/releases/tag/4.0.6 
Yes this is the link from where i downloaded this morning
And it seems to be v4.0.6

**Comment by alanhamlett** [comment]
Oh, thanks for the traceback. I must have misread it. It's fixed in v4.0.8.
