### ISSUE TITLE
dummy-download-handle

### ISSUE THREAD

**Issue by jradziwon** [wakatime/netbeans-wakatime#2]
java.lang.ClassCastException: org.netbeans.modules.autoupdate.services.FeatureUpdateElementImpl cannot be cast to org.netbeans.modules.autoupdate.services.ModuleUpdateElementImpl
	at org.netbeans.modules.autoupdate.services.InstallManager.getInstallDir(InstallManager.java:260)
	at org.netbeans.modules.autoupdate.services.InstallManager.findTargetDirectory(InstallManager.java:105)
	at org.netbeans.modules.autoupdate.services.InstallSupportImpl$1.call(InstallSupportImpl.java:156)
	at org.netbeans.modules.autoupdate.services.InstallSupportImpl$1.call(InstallSupportImpl.java:142)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused: java.util.concurrent.ExecutionException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:188)
[catch] at org.netbeans.modules.autoupdate.services.InstallSupportImpl.doDownload(InstallSupportImpl.java:194)
	at org.netbeans.api.autoupdate.InstallSupport.doDownload(InstallSupport.java:98)
	at org.wakatime.netbeans.plugin.UpdateHandler.doDownload(UpdateHandler.java:294)
	at org.wakatime.netbeans.plugin.UpdateHandler.handleInstall(UpdateHandler.java:166)
	at org.wakatime.netbeans.plugin.UpdateHandler.checkAndHandleUpdates(UpdateHandler.java:125)
	at org.wakatime.netbeans.plugin.WakaTime$2.run(WakaTime.java:120)
	at org.netbeans.core.windows.WindowManagerImpl$Exclusive$1.run(WindowManagerImpl.java:1563)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:733)
	at java.awt.EventQueue.access$200(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:694)
	at java.awt.EventQueue$3.run(EventQueue.java:692)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:703)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)

**Comment by meridius** [comment]
I still have this issue on Linux on:
Netbeans: 8.0.2 (Build 201411102027)

Plugin:
Version: 1.0 
Source: 1419536623_netbeans-wakatime-v3.0.1.nbm

python 3.4.2-2

I have also tried removing the Netbeans' config directory and re-installing the plugin. 
No matter how long I wait, the plugin is still showing the loading bar - the same as https://github.com/wakatime/netbeans-wakatime/issues/2#issuecomment-66175253

**Comment by iliaz** [comment]
Same issue here, 
Win7
NetBeans IDE 8.0.2 (Build 201411181905)

Version: 3.0.1
Source: 1419536623_netbeans-wakatime-v3.0.1.nbm

**Comment by ftaleman** [comment]
Same problem... 
Product Version: NetBeans IDE 8.0.2 (Build 201411181905)
Java: 1.7.0_55; Java HotSpot(TM) 64-Bit Server VM 24.55-b03
Runtime: Java(TM) SE Runtime Environment 1.7.0_55-b13
System: Windows 8 version 6.2 running on amd64; Cp1252; en_US (nb)

Version: 3.0.1
Source: 1419536623_netbeans-wakatime-v3.0.1.nbm

**Comment by Trejjam** [comment]
Same issue
Product Version: NetBeans IDE 8.0.2 (Build 201411102027)
Updates: NetBeans IDE is updated to version NetBeans 8.0.2 Patch 1
Java: 1.8.0_40; Java HotSpot(TM) 64-Bit Server VM 25.40-b25
Runtime: Java(TM) SE Runtime Environment 1.8.0_40-b25
System: Linux version 3.18.6-1-ARCH running on amd64; UTF-8; cs_CZ (nb)

**Comment by alanhamlett** [comment]
Fixed with #5
