### ISSUE TITLE
Exception thrown after try to connnect to download new WakaTime plugin

### ISSUE THREAD

**Issue by hexin** [wakatime/netbeans-wakatime#4]
java.lang.ClassCastException: org.netbeans.modules.autoupdate.services.FeatureUpdateElementImpl cannot be cast to org.netbeans.modules.autoupdate.services.ModuleUpdateElementImpl
	at org.netbeans.modules.autoupdate.services.InstallManager.getInstallDir(InstallManager.java:260)
	at org.netbeans.modules.autoupdate.services.InstallManager.findTargetDirectory(InstallManager.java:105)
	at org.netbeans.modules.autoupdate.services.InstallSupportImpl$1.call(InstallSupportImpl.java:156)
	at org.netbeans.modules.autoupdate.services.InstallSupportImpl$1.call(InstallSupportImpl.java:142)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
Caused: java.util.concurrent.ExecutionException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:188)
[catch] at org.netbeans.modules.autoupdate.services.InstallSupportImpl.doDownload(InstallSupportImpl.java:194)
	at org.netbeans.api.autoupdate.InstallSupport.doDownload(InstallSupport.java:98)
	at org.wakatime.netbeans.plugin.UpdateHandler.doDownload(UpdateHandler.java:327)
	at org.wakatime.netbeans.plugin.UpdateHandler.handleInstall(UpdateHandler.java:167)
	at org.wakatime.netbeans.plugin.UpdateHandler.checkAndHandleUpdates(UpdateHandler.java:126)
	at org.wakatime.netbeans.plugin.WakaTime$2.run(WakaTime.java:116)
	at org.netbeans.core.windows.WindowManagerImpl$Exclusive$1.run(WindowManagerImpl.java:1563)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:251)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:733)
	at java.awt.EventQueue.access$200(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:694)
	at java.awt.EventQueue$3.run(EventQueue.java:692)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:703)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)

**Comment by alanhamlett** [comment]
This should be fixed in v3.0.5 of the plugin.

**Comment by fredw** [comment]
I installed v3.0.5 and it occour too.

**Comment by alanhamlett** [comment]
@fredw can you paste a traceback of the exception?

**Comment by fredw** [comment]
@alanhamlett I don't have it anymore, but I bought before and is exactly same as @hexin log.

**Comment by alanhamlett** [comment]
The line numbers in that traceback don't match the current version of the code, so this traceback must be from an old version of the plugin.
