### ISSUE TITLE
NullPointerException in UpdateHandler

### ISSUE THREAD

**Issue by Lolmewn** [wakatime/netbeans-wakatime#7]
After installing the plugin I restarted my Netbeans. It then prompted me to input my API key, which I copy-pasted in there from the WakaTime Netbeans Plugin install tutorial. It then gave an exception:

```
java.lang.NullPointerException 
    at org.wakatime.netbeans.plugin.UpdateHandler.checkAndHandleUpdates(UpdateHandler.java:143)
	at org.wakatime.netbeans.plugin.WakaTime$2.run(WakaTime.java:126)
[catch] at org.netbeans.core.windows.WindowManagerImpl$Exclusive$1.run(WindowManagerImpl.java:1563)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by Ganzal** [comment]
same issue on every nb startup

**Comment by alanhamlett** [comment]
Just released v3.0.7, does this still happen with the new version?

**Comment by Lolmewn** [comment]
No, it seems to work now. Data is getting to the dashboard too!

**Comment by alanhamlett** [comment]
:+1: :smile:
