### ISSUE TITLE
Unable to activate plugin v4.0 with development versions of NB

### ISSUE THREAD

**Issue by Ganzal** [wakatime/netbeans-wakatime#9]
Tested versions:
* 8.1beta
* 8.1rc
* nightly 201510040002
* nightly 201510110923

Restarting IDE (v8.1rc) after plugin update shows this message:
could not install some modules: WakaTime - The module JNA Platform was requested in implementation version "201408251540" but only "201510012201" was found.

Doing "Tools -> Plugins -> Installed -> [check] Show details -> [check] WakaTime -> Activate" puts this into log file:

INFO [org.netbeans.modules.autoupdate.ui.wizards.UninstallStep]: java.lang.IllegalArgumentException: Not all requested modules can be enabled: [StandardModule:org.wakatime.netbeans.plugin jarFile: /home/ganzal/.netbeans/8.1rc/modules/org-wakatime-netbeans-plugin.jar]
java.lang.IllegalArgumentException: Not all requested modules can be enabled: [StandardModule:org.wakatime.netbeans.plugin jarFile: /home/ganzal/.netbeans/8.1rc/modules/org-wakatime-netbeans-plugin.jar]
	at org.netbeans.ModuleManager.enable(ModuleManager.java:1181)
	at org.netbeans.ModuleManager.enable(ModuleManager.java:1157)
	at org.netbeans.modules.autoupdate.services.OperationSupportImpl$ForEnable.enable(OperationSupportImpl.java:190)
Caused: org.netbeans.api.autoupdate.OperationException[ENABLE]: Not all requested modules can be enabled: [StandardModule:org.wakatime.netbeans.plugin jarFile: /home/ganzal/.netbeans/8.1rc/modules/org-wakatime-netbeans-plugin.jar]
	at org.netbeans.modules.autoupdate.services.OperationSupportImpl$ForEnable.enable(OperationSupportImpl.java:193)
	at org.netbeans.modules.autoupdate.services.OperationSupportImpl$ForEnable.access$1000(OperationSupportImpl.java:123)
	at org.netbeans.modules.autoupdate.services.OperationSupportImpl$ForEnable$1.run(OperationSupportImpl.java:163)
	at org.netbeans.modules.autoupdate.services.OperationSupportImpl$ForEnable$1.run(OperationSupportImpl.java:160)
	at org.netbeans.modules.openide.util.DefaultMutexImplementation.writeAccess(DefaultMutexImplementation.java:293)
	at org.openide.util.Mutex.writeAccess(Mutex.java:299)
	at org.netbeans.modules.autoupdate.services.OperationSupportImpl$ForEnable.doOperation(OperationSupportImpl.java:160)
	at org.netbeans.api.autoupdate.OperationSupport.doOperation(OperationSupport.java:70)
[catch] at org.netbeans.modules.autoupdate.ui.wizards.UninstallStep.handleAction(UninstallStep.java:206)
	at org.netbeans.modules.autoupdate.ui.wizards.UninstallStep.doAction(UninstallStep.java:140)
	at org.netbeans.modules.autoupdate.ui.wizards.UninstallStep.access$000(UninstallStep.java:71)
	at org.netbeans.modules.autoupdate.ui.wizards.UninstallStep$1.propertyChange(UninstallStep.java:108)
	at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:327)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:263)
	at java.awt.Component.firePropertyChange(Component.java:8430)
	at org.netbeans.modules.autoupdate.ui.wizards.OperationPanel.access$200(OperationPanel.java:69)
	at org.netbeans.modules.autoupdate.ui.wizards.OperationPanel$1.run(OperationPanel.java:107)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1443)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:68)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:303)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2058)

Product info (if its needs) for 8.1rc:

  Product Version         = NetBeans IDE 8.1 RC (Build 201510012201) (#be48724de91f)
  Operating System        = Linux version 3.13.0-65-generic running on amd64 
  Java; VM; Vendor        = 1.8.0_60; Java HotSpot(TM) 64-Bit Server VM 25.60-b23; Oracle Corporation
  Runtime                 = Java(TM) SE Runtime Environment 1.8.0_60-b27
  Java Home               = /usr/lib/jvm/java-8-oracle/jre
  System Locale; Encoding = en_US (nb); UTF-8

**Comment by alanhamlett** [comment]
Can you try with v4.0.1 of the plugin?

**Comment by Ganzal** [comment]
Updated with no warnings but on IDE restart catched following exception:

java.lang.ClassNotFoundException: com.sun.jna.win32.StdCallLibrary
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.netbeans.ProxyClassLoader.loadClass(ProxyClassLoader.java:222)
Caused: java.lang.ClassNotFoundException: com.sun.jna.win32.StdCallLibrary starting from ModuleCL@85d481c[org.wakatime.netbeans.plugin] with possible defining loaders [ModuleCL@52b0afc7[org.netbeans.libs.svnClientAdapter.svnkit], ModuleCL@1cac8886[org.netbeans.libs.jna]] and declared parents [ModuleCL@1047f902[org.netbeans.modules.projectapi], org.netbeans.MainImpl$BootClassLoader@238e0d81, ModuleCL@25eccaa2[org.openide.actions], ModuleCL@66c38e2d[org.netbeans.modules.options.api], ModuleCL@1111e86a[org.openide.dialogs], ModuleCL@bfd2296[org.netbeans.modules.autoupdate.services], ModuleCL@4c382fea[org.netbeans.api.progress], ModuleCL@221a403d[org.netbeans.modules.editor.document], ModuleCL@6b3fab37[org.openide.windows], ModuleCL@7cfdae8d[org.openide.nodes], ...10 more]
	at org.netbeans.ProxyClassLoader.loadClass(ProxyClassLoader.java:224)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
Caused: java.lang.NoClassDefFoundError: com/sun/jna/win32/StdCallLibrary
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at org.netbeans.JarClassLoader.doLoadClass(JarClassLoader.java:311)
	at org.netbeans.ProxyClassLoader.selfLoadClass(ProxyClassLoader.java:259)
Caused: java.lang.NoClassDefFoundError: com/sun/jna/win32/StdCallLibrary while loading com.sun.jna.platform.win32.WinReg; see http://wiki.netbeans.org/DevFaqTroubleshootClassNotFound
	at org.netbeans.ProxyClassLoader.selfLoadClass(ProxyClassLoader.java:263)
	at org.netbeans.ProxyClassLoader.loadClass(ProxyClassLoader.java:217)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.wakatime.netbeans.plugin.Dependencies.getPythonLocation(Dependencies.java:58)
	at org.wakatime.netbeans.plugin.Dependencies.isPythonInstalled(Dependencies.java:36)
	at org.wakatime.netbeans.plugin.WakaTime.run(WakaTime.java:82)
	at org.netbeans.core.windows.WindowManagerImpl$Exclusive$1.run(WindowManagerImpl.java:1563)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
[catch] at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by alanhamlett** [comment]
Oops, forgot to bundle the jna jar in the plugin release. It's fixed in v4.0.2!

**Comment by Ganzal** [comment]
It works! Thx!
